/* tslint:disable */
/* eslint-disable */
/**
 * SecureStream API
 * SecureStream APIの仕様書です
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
    /**
     * 新しいパスワード
     * @type {string}
     * @memberof ChangePassword
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ChangeUsername
 */
export interface ChangeUsername {
    /**
     * 認証コード
     * @type {string}
     * @memberof ChangeUsername
     */
    'code': string;
}
/**
 * 
 * @export
 * @interface Model400Error
 */
export interface Model400Error {
    /**
     * 
     * @type {Model400ErrorError}
     * @memberof Model400Error
     */
    'error': Model400ErrorError;
}
/**
 * 
 * @export
 * @interface Model400ErrorError
 */
export interface Model400ErrorError {
    /**
     * リクエストID
     * @type {string}
     * @memberof Model400ErrorError
     */
    'request_id': string;
    /**
     * エラーコード | エラーコード | 説明 | |-|-| | 400-001 | 入力値が不正 | | 400-002 | パスワードが弱い | 
     * @type {string}
     * @memberof Model400ErrorError
     */
    'code': Model400ErrorErrorCodeEnum;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof Model400ErrorError
     */
    'message': string;
}

export const Model400ErrorErrorCodeEnum = {
    _400001: '400-001'
} as const;

export type Model400ErrorErrorCodeEnum = typeof Model400ErrorErrorCodeEnum[keyof typeof Model400ErrorErrorCodeEnum];

/**
 * 
 * @export
 * @interface Model401Error
 */
export interface Model401Error {
    /**
     * 
     * @type {Model401ErrorError}
     * @memberof Model401Error
     */
    'error': Model401ErrorError;
}
/**
 * 
 * @export
 * @interface Model401ErrorError
 */
export interface Model401ErrorError {
    /**
     * リクエストID
     * @type {string}
     * @memberof Model401ErrorError
     */
    'request_id': string;
    /**
     * エラーコード | エラーコード | 説明 | |-|-| | 401-001 | アクセストークン無効 | 
     * @type {string}
     * @memberof Model401ErrorError
     */
    'code': Model401ErrorErrorCodeEnum;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof Model401ErrorError
     */
    'message': string;
}

export const Model401ErrorErrorCodeEnum = {
    _401001: '401-001'
} as const;

export type Model401ErrorErrorCodeEnum = typeof Model401ErrorErrorCodeEnum[keyof typeof Model401ErrorErrorCodeEnum];

/**
 * 
 * @export
 * @interface Model500Error
 */
export interface Model500Error {
    /**
     * 
     * @type {Model500ErrorError}
     * @memberof Model500Error
     */
    'error': Model500ErrorError;
}
/**
 * 
 * @export
 * @interface Model500ErrorError
 */
export interface Model500ErrorError {
    /**
     * リクエストID
     * @type {string}
     * @memberof Model500ErrorError
     */
    'request_id': string;
    /**
     * エラーコード | エラーコード | 説明 | |-|-| | 500-001 | 予期せぬエラー | 
     * @type {string}
     * @memberof Model500ErrorError
     */
    'code': Model500ErrorErrorCodeEnum;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof Model500ErrorError
     */
    'message': string;
}

export const Model500ErrorErrorCodeEnum = {
    _500001: '500-001'
} as const;

export type Model500ErrorErrorCodeEnum = typeof Model500ErrorErrorCodeEnum[keyof typeof Model500ErrorErrorCodeEnum];

/**
 * 
 * @export
 * @interface RegisterWebauthnRequest
 */
export interface RegisterWebauthnRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'flowId': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'rawId': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'type': string;
    /**
     * 
     * @type {RegisterWebauthnRequestResponse}
     * @memberof RegisterWebauthnRequest
     */
    'response': RegisterWebauthnRequestResponse;
}
/**
 * 
 * @export
 * @interface RegisterWebauthnRequestResponse
 */
export interface RegisterWebauthnRequestResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequestResponse
     */
    'clientDataJSON'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequestResponse
     */
    'attestationObject'?: string;
}
/**
 * 
 * @export
 * @interface RequestChangeUsername
 */
export interface RequestChangeUsername {
    /**
     * 新しいUsername
     * @type {string}
     * @memberof RequestChangeUsername
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistration
 */
export interface RequestWebauthnRegistration {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'flowId': string;
    /**
     * 
     * @type {RequestWebauthnRegistrationRp}
     * @memberof RequestWebauthnRegistration
     */
    'rp': RequestWebauthnRegistrationRp;
    /**
     * 
     * @type {RequestWebauthnRegistrationUser}
     * @memberof RequestWebauthnRegistration
     */
    'user': RequestWebauthnRegistrationUser;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'challenge': string;
    /**
     * 
     * @type {Array<RequestWebauthnRegistrationPubKeyCredParamsInner>}
     * @memberof RequestWebauthnRegistration
     */
    'pubKeyCredParams': Array<RequestWebauthnRegistrationPubKeyCredParamsInner>;
    /**
     * 
     * @type {number}
     * @memberof RequestWebauthnRegistration
     */
    'timeout': number;
    /**
     * 
     * @type {Array<RequestWebauthnRegistrationExcludeCredentialsInner>}
     * @memberof RequestWebauthnRegistration
     */
    'excludeCredentials': Array<RequestWebauthnRegistrationExcludeCredentialsInner>;
    /**
     * 
     * @type {RequestWebauthnRegistrationAuthenticatorSelection}
     * @memberof RequestWebauthnRegistration
     */
    'authenticatorSelection': RequestWebauthnRegistrationAuthenticatorSelection;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'attestation': string;
    /**
     * 
     * @type {RequestWebauthnRegistrationExtensions}
     * @memberof RequestWebauthnRegistration
     */
    'extensions'?: RequestWebauthnRegistrationExtensions;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationAuthenticatorSelection
 */
export interface RequestWebauthnRegistrationAuthenticatorSelection {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'authenticatorAttachment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'requireResidentKey'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'userVerification'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationExcludeCredentialsInner
 */
export interface RequestWebauthnRegistrationExcludeCredentialsInner {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExcludeCredentialsInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExcludeCredentialsInner
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationExtensions
 */
export interface RequestWebauthnRegistrationExtensions {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'appid'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'authnSel'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'exts'?: boolean;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationPubKeyCredParamsInner
 */
export interface RequestWebauthnRegistrationPubKeyCredParamsInner {
    /**
     * 
     * @type {number}
     * @memberof RequestWebauthnRegistrationPubKeyCredParamsInner
     */
    'alg'?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationPubKeyCredParamsInner
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationRp
 */
export interface RequestWebauthnRegistrationRp {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationRp
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationRp
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationUser
 */
export interface RequestWebauthnRegistrationUser {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'displayName'?: string;
}
/**
 * 
 * @export
 * @interface SocialLoginUrls
 */
export interface SocialLoginUrls {
    /**
     * Googleの認可コードリクエストURL
     * @type {string}
     * @memberof SocialLoginUrls
     */
    'google': string;
    /**
     * GitHubの認可コードリクエストURL
     * @type {string}
     * @memberof SocialLoginUrls
     */
    'github': string;
}

/**
 * PasswordApi - axios parameter creator
 * @export
 */
export const PasswordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * パスワードの変更を行います。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (changePassword: ChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'changePassword' is not null or undefined
            assertParamExists('changePassword', 'changePassword', changePassword)
            const localVarPath = `/api/v1/users/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PasswordApi - functional programming interface
 * @export
 */
export const PasswordApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PasswordApiAxiosParamCreator(configuration)
    return {
        /**
         * パスワードの変更を行います。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(changePassword: ChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(changePassword, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PasswordApi.changePassword']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PasswordApi - factory interface
 * @export
 */
export const PasswordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PasswordApiFp(configuration)
    return {
        /**
         * パスワードの変更を行います。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(changePassword: ChangePassword, options?: any): AxiosPromise<void> {
            return localVarFp.changePassword(changePassword, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PasswordApi - object-oriented interface
 * @export
 * @class PasswordApi
 * @extends {BaseAPI}
 */
export class PasswordApi extends BaseAPI {
    /**
     * パスワードの変更を行います。
     * @summary 変更
     * @param {ChangePassword} changePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PasswordApi
     */
    public changePassword(changePassword: ChangePassword, options?: RawAxiosRequestConfig) {
        return PasswordApiFp(this.configuration).changePassword(changePassword, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SocialLoginApi - axios parameter creator
 * @export
 */
export const SocialLoginApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 連携済みのソーシャルログインの連携を解除します。
         * @summary 連携解除
         * @param {string} provider プロバイダ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSocialLogin: async (provider: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('deleteSocialLogin', 'provider', provider)
            const localVarPath = `/api/v1/users/social_login/{provider}`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 各種ソーシャルログインの認可リクエストURLを取得します
         * @summary 認可リクエスト一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSocialLoginUrl: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/social_login/urls`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 各種ソーシャルログインの認可コードからアクセストークンを取得します（バックエンド用）
         * @summary 認可コードリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestAuthorizationCode: async (provider: string, code: string, state?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('requestAuthorizationCode', 'provider', provider)
            // verify required parameter 'code' is not null or undefined
            assertParamExists('requestAuthorizationCode', 'code', code)
            const localVarPath = `/api/v1/users/social_login/code/{provider}`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 各種ソーシャルログインの認可コードを認証アプリケーション側にリダイレクトします
         * @summary ログインリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {string} [loginChallenge] IdP側の認証に必要なチャレンジコード
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestAuthorizationCodeForLogin: async (provider: string, code: string, state?: string, loginChallenge?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('requestAuthorizationCodeForLogin', 'provider', provider)
            // verify required parameter 'code' is not null or undefined
            assertParamExists('requestAuthorizationCodeForLogin', 'code', code)
            const localVarPath = `/api/v1/users/social_login/login/code/{provider}`
                .replace(`{${"provider"}}`, encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (loginChallenge !== undefined) {
                localVarQueryParameter['login_challenge'] = loginChallenge;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SocialLoginApi - functional programming interface
 * @export
 */
export const SocialLoginApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SocialLoginApiAxiosParamCreator(configuration)
    return {
        /**
         * 連携済みのソーシャルログインの連携を解除します。
         * @summary 連携解除
         * @param {string} provider プロバイダ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSocialLogin(provider: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSocialLogin(provider, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SocialLoginApi.deleteSocialLogin']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 各種ソーシャルログインの認可リクエストURLを取得します
         * @summary 認可リクエスト一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSocialLoginUrl(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SocialLoginUrls>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSocialLoginUrl(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SocialLoginApi.getSocialLoginUrl']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 各種ソーシャルログインの認可コードからアクセストークンを取得します（バックエンド用）
         * @summary 認可コードリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestAuthorizationCode(provider: string, code: string, state?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestAuthorizationCode(provider, code, state, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SocialLoginApi.requestAuthorizationCode']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 各種ソーシャルログインの認可コードを認証アプリケーション側にリダイレクトします
         * @summary ログインリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {string} [loginChallenge] IdP側の認証に必要なチャレンジコード
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestAuthorizationCodeForLogin(provider: string, code: string, state?: string, loginChallenge?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestAuthorizationCodeForLogin(provider, code, state, loginChallenge, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SocialLoginApi.requestAuthorizationCodeForLogin']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * SocialLoginApi - factory interface
 * @export
 */
export const SocialLoginApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SocialLoginApiFp(configuration)
    return {
        /**
         * 連携済みのソーシャルログインの連携を解除します。
         * @summary 連携解除
         * @param {string} provider プロバイダ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSocialLogin(provider: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteSocialLogin(provider, options).then((request) => request(axios, basePath));
        },
        /**
         * 各種ソーシャルログインの認可リクエストURLを取得します
         * @summary 認可リクエスト一覧取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSocialLoginUrl(options?: any): AxiosPromise<SocialLoginUrls> {
            return localVarFp.getSocialLoginUrl(options).then((request) => request(axios, basePath));
        },
        /**
         * 各種ソーシャルログインの認可コードからアクセストークンを取得します（バックエンド用）
         * @summary 認可コードリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestAuthorizationCode(provider: string, code: string, state?: string, options?: any): AxiosPromise<void> {
            return localVarFp.requestAuthorizationCode(provider, code, state, options).then((request) => request(axios, basePath));
        },
        /**
         * 各種ソーシャルログインの認可コードを認証アプリケーション側にリダイレクトします
         * @summary ログインリクエスト
         * @param {string} provider プロバイダ
         * @param {string} code 認可コード
         * @param {string} [state] state
         * @param {string} [loginChallenge] IdP側の認証に必要なチャレンジコード
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestAuthorizationCodeForLogin(provider: string, code: string, state?: string, loginChallenge?: string, options?: any): AxiosPromise<void> {
            return localVarFp.requestAuthorizationCodeForLogin(provider, code, state, loginChallenge, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SocialLoginApi - object-oriented interface
 * @export
 * @class SocialLoginApi
 * @extends {BaseAPI}
 */
export class SocialLoginApi extends BaseAPI {
    /**
     * 連携済みのソーシャルログインの連携を解除します。
     * @summary 連携解除
     * @param {string} provider プロバイダ
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialLoginApi
     */
    public deleteSocialLogin(provider: string, options?: RawAxiosRequestConfig) {
        return SocialLoginApiFp(this.configuration).deleteSocialLogin(provider, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 各種ソーシャルログインの認可リクエストURLを取得します
     * @summary 認可リクエスト一覧取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialLoginApi
     */
    public getSocialLoginUrl(options?: RawAxiosRequestConfig) {
        return SocialLoginApiFp(this.configuration).getSocialLoginUrl(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 各種ソーシャルログインの認可コードからアクセストークンを取得します（バックエンド用）
     * @summary 認可コードリクエスト
     * @param {string} provider プロバイダ
     * @param {string} code 認可コード
     * @param {string} [state] state
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialLoginApi
     */
    public requestAuthorizationCode(provider: string, code: string, state?: string, options?: RawAxiosRequestConfig) {
        return SocialLoginApiFp(this.configuration).requestAuthorizationCode(provider, code, state, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 各種ソーシャルログインの認可コードを認証アプリケーション側にリダイレクトします
     * @summary ログインリクエスト
     * @param {string} provider プロバイダ
     * @param {string} code 認可コード
     * @param {string} [state] state
     * @param {string} [loginChallenge] IdP側の認証に必要なチャレンジコード
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SocialLoginApi
     */
    public requestAuthorizationCodeForLogin(provider: string, code: string, state?: string, loginChallenge?: string, options?: RawAxiosRequestConfig) {
        return SocialLoginApiFp(this.configuration).requestAuthorizationCodeForLogin(provider, code, state, loginChallenge, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsernameApi - axios parameter creator
 * @export
 */
export const UsernameApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeUsername} requestChangeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId: async (requestChangeUsername: RequestChangeUsername, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestChangeUsername' is not null or undefined
            assertParamExists('requestChangeLoginId', 'requestChangeUsername', requestChangeUsername)
            const localVarPath = `/api/v1/users/username/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestChangeUsername, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangeUsername} changeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId_1: async (changeUsername: ChangeUsername, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'changeUsername' is not null or undefined
            assertParamExists('requestChangeLoginId_1', 'changeUsername', changeUsername)
            const localVarPath = `/api/v1/users/username`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changeUsername, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsernameApi - functional programming interface
 * @export
 */
export const UsernameApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsernameApiAxiosParamCreator(configuration)
    return {
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeUsername} requestChangeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestChangeLoginId(requestChangeUsername: RequestChangeUsername, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestChangeLoginId(requestChangeUsername, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['UsernameApi.requestChangeLoginId']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangeUsername} changeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestChangeLoginId_1(changeUsername: ChangeUsername, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestChangeLoginId_1(changeUsername, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['UsernameApi.requestChangeLoginId_1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * UsernameApi - factory interface
 * @export
 */
export const UsernameApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsernameApiFp(configuration)
    return {
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeUsername} requestChangeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId(requestChangeUsername: RequestChangeUsername, options?: any): AxiosPromise<void> {
            return localVarFp.requestChangeLoginId(requestChangeUsername, options).then((request) => request(axios, basePath));
        },
        /**
         * Usernameの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangeUsername} changeUsername 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId_1(changeUsername: ChangeUsername, options?: any): AxiosPromise<void> {
            return localVarFp.requestChangeLoginId_1(changeUsername, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsernameApi - object-oriented interface
 * @export
 * @class UsernameApi
 * @extends {BaseAPI}
 */
export class UsernameApi extends BaseAPI {
    /**
     * Usernameの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
     * @summary 変更要求
     * @param {RequestChangeUsername} requestChangeUsername 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsernameApi
     */
    public requestChangeLoginId(requestChangeUsername: RequestChangeUsername, options?: RawAxiosRequestConfig) {
        return UsernameApiFp(this.configuration).requestChangeLoginId(requestChangeUsername, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Usernameの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
     * @summary 変更
     * @param {ChangeUsername} changeUsername 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsernameApi
     */
    public requestChangeLoginId_1(changeUsername: ChangeUsername, options?: RawAxiosRequestConfig) {
        return UsernameApiFp(this.configuration).requestChangeLoginId_1(changeUsername, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WebauthnApi - axios parameter creator
 * @export
 */
export const WebauthnApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebauthn: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/webauthn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerWebauthn: async (registerWebauthnRequest: RegisterWebauthnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerWebauthnRequest' is not null or undefined
            assertParamExists('registerWebauthn', 'registerWebauthnRequest', registerWebauthnRequest)
            const localVarPath = `/api/v1/users/webauthn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerWebauthnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestWebauthnRegistration: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/webauthn/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebauthnApi - functional programming interface
 * @export
 */
export const WebauthnApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebauthnApiAxiosParamCreator(configuration)
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWebauthn(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWebauthn(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.deleteWebauthn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerWebauthn(registerWebauthnRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.registerWebauthn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestWebauthnRegistration(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequestWebauthnRegistration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestWebauthnRegistration(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.requestWebauthnRegistration']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * WebauthnApi - factory interface
 * @export
 */
export const WebauthnApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebauthnApiFp(configuration)
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebauthn(options?: any): AxiosPromise<void> {
            return localVarFp.deleteWebauthn(options).then((request) => request(axios, basePath));
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: any): AxiosPromise<void> {
            return localVarFp.registerWebauthn(registerWebauthnRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestWebauthnRegistration(options?: any): AxiosPromise<RequestWebauthnRegistration> {
            return localVarFp.requestWebauthnRegistration(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebauthnApi - object-oriented interface
 * @export
 * @class WebauthnApi
 * @extends {BaseAPI}
 */
export class WebauthnApi extends BaseAPI {
    /**
     * 登録済みのWebauthnのcredentialを全て削除します。
     * @summary 全件削除
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public deleteWebauthn(options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).deleteWebauthn(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Webauthnの登録を行います。
     * @summary 登録
     * @param {RegisterWebauthnRequest} registerWebauthnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).registerWebauthn(registerWebauthnRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Webauthn登録のために認証器に送信する情報を取得します。
     * @summary 登録要求
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public requestWebauthnRegistration(options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).requestWebauthnRegistration(options).then((request) => request(this.axios, this.basePath));
    }
}



