/* tslint:disable */
/* eslint-disable */
/**
 * SecureStream API
 * SecureStream APIの仕様書です
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface WebauthnRegistration
 */
export interface WebauthnRegistration {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration
     */
    'flowId': string;
    /**
     * 
     * @type {WebauthnRegistrationRp}
     * @memberof WebauthnRegistration
     */
    'rp': WebauthnRegistrationRp;
    /**
     * 
     * @type {WebauthnRegistrationUser}
     * @memberof WebauthnRegistration
     */
    'user': WebauthnRegistrationUser;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration
     */
    'challenge': string;
    /**
     * 
     * @type {Array<WebauthnRegistrationPubKeyCredParamsInner>}
     * @memberof WebauthnRegistration
     */
    'pubKeyCredParams': Array<WebauthnRegistrationPubKeyCredParamsInner>;
    /**
     * 
     * @type {number}
     * @memberof WebauthnRegistration
     */
    'timeout': number;
    /**
     * 
     * @type {Array<WebauthnRegistrationPubKeyCredParamsInner>}
     * @memberof WebauthnRegistration
     */
    'excludeCredentials': Array<WebauthnRegistrationPubKeyCredParamsInner>;
    /**
     * 
     * @type {WebauthnRegistrationAuthenticatorSelection}
     * @memberof WebauthnRegistration
     */
    'authenticatorSelection': WebauthnRegistrationAuthenticatorSelection;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration
     */
    'attestation': string;
    /**
     * 
     * @type {WebauthnRegistrationExtensions}
     * @memberof WebauthnRegistration
     */
    'extensions'?: WebauthnRegistrationExtensions;
}
/**
 * 
 * @export
 * @interface WebauthnRegistration1
 */
export interface WebauthnRegistration1 {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1
     */
    'flowId': string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1
     */
    'rawId': string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1
     */
    'type': string;
    /**
     * 
     * @type {WebauthnRegistration1Response}
     * @memberof WebauthnRegistration1
     */
    'response': WebauthnRegistration1Response;
}
/**
 * 
 * @export
 * @interface WebauthnRegistration1Response
 */
export interface WebauthnRegistration1Response {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1Response
     */
    'clientDataJSON'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistration1Response
     */
    'attestationObject'?: string;
}
/**
 * 
 * @export
 * @interface WebauthnRegistrationAuthenticatorSelection
 */
export interface WebauthnRegistrationAuthenticatorSelection {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationAuthenticatorSelection
     */
    'authenticatorAttachment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebauthnRegistrationAuthenticatorSelection
     */
    'requireResidentKey'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationAuthenticatorSelection
     */
    'userVerification'?: string;
}
/**
 * 
 * @export
 * @interface WebauthnRegistrationExtensions
 */
export interface WebauthnRegistrationExtensions {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationExtensions
     */
    'appid'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationExtensions
     */
    'authnSel'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebauthnRegistrationExtensions
     */
    'exts'?: boolean;
}
/**
 * 
 * @export
 * @interface WebauthnRegistrationPubKeyCredParamsInner
 */
export interface WebauthnRegistrationPubKeyCredParamsInner {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationPubKeyCredParamsInner
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface WebauthnRegistrationRp
 */
export interface WebauthnRegistrationRp {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationRp
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationRp
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface WebauthnRegistrationUser
 */
export interface WebauthnRegistrationUser {
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebauthnRegistrationUser
     */
    'displayName'?: string;
}

/**
 * WebauthnApi - axios parameter creator
 * @export
 */
export const WebauthnApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 登録要求リクエスト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webauthn: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webauthn/request`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 登録リクエスト
         * @param {WebauthnRegistration1} [webauthnRegistration1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webauthn_1: async (webauthnRegistration1?: WebauthnRegistration1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/webauthn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(webauthnRegistration1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebauthnApi - functional programming interface
 * @export
 */
export const WebauthnApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebauthnApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 登録要求リクエスト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async webauthn(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WebauthnRegistration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.webauthn(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.webauthn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary 登録リクエスト
         * @param {WebauthnRegistration1} [webauthnRegistration1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async webauthn_1(webauthnRegistration1?: WebauthnRegistration1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.webauthn_1(webauthnRegistration1, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.webauthn_1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * WebauthnApi - factory interface
 * @export
 */
export const WebauthnApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebauthnApiFp(configuration)
    return {
        /**
         * 
         * @summary 登録要求リクエスト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webauthn(options?: any): AxiosPromise<WebauthnRegistration> {
            return localVarFp.webauthn(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 登録リクエスト
         * @param {WebauthnRegistration1} [webauthnRegistration1] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        webauthn_1(webauthnRegistration1?: WebauthnRegistration1, options?: any): AxiosPromise<void> {
            return localVarFp.webauthn_1(webauthnRegistration1, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebauthnApi - object-oriented interface
 * @export
 * @class WebauthnApi
 * @extends {BaseAPI}
 */
export class WebauthnApi extends BaseAPI {
    /**
     * 
     * @summary 登録要求リクエスト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public webauthn(options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).webauthn(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 登録リクエスト
     * @param {WebauthnRegistration1} [webauthnRegistration1] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public webauthn_1(webauthnRegistration1?: WebauthnRegistration1, options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).webauthn_1(webauthnRegistration1, options).then((request) => request(this.axios, this.basePath));
    }
}



