/* tslint:disable */
/* eslint-disable */
/**
 * SecureStream API
 * SecureStream APIの仕様書です
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
    /**
     * 認証コード
     * @type {string}
     * @memberof ChangePassword
     */
    'code': string;
}
/**
 * 
 * @export
 * @interface RegisterWebauthnRequest
 */
export interface RegisterWebauthnRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'flowId': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'rawId': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequest
     */
    'type': string;
    /**
     * 
     * @type {RegisterWebauthnRequestResponse}
     * @memberof RegisterWebauthnRequest
     */
    'response': RegisterWebauthnRequestResponse;
}
/**
 * 
 * @export
 * @interface RegisterWebauthnRequestResponse
 */
export interface RegisterWebauthnRequestResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequestResponse
     */
    'clientDataJSON'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterWebauthnRequestResponse
     */
    'attestationObject'?: string;
}
/**
 * 
 * @export
 * @interface RequestChangeLoginId
 */
export interface RequestChangeLoginId {
    /**
     * 新しいログインID
     * @type {string}
     * @memberof RequestChangeLoginId
     */
    'login_id': string;
}
/**
 * 
 * @export
 * @interface RequestChangePassword
 */
export interface RequestChangePassword {
    /**
     * 新しいパスワード
     * @type {string}
     * @memberof RequestChangePassword
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistration
 */
export interface RequestWebauthnRegistration {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'flowId': string;
    /**
     * 
     * @type {RequestWebauthnRegistrationRp}
     * @memberof RequestWebauthnRegistration
     */
    'rp': RequestWebauthnRegistrationRp;
    /**
     * 
     * @type {RequestWebauthnRegistrationUser}
     * @memberof RequestWebauthnRegistration
     */
    'user': RequestWebauthnRegistrationUser;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'challenge': string;
    /**
     * 
     * @type {Array<RequestWebauthnRegistrationPubKeyCredParamsInner>}
     * @memberof RequestWebauthnRegistration
     */
    'pubKeyCredParams': Array<RequestWebauthnRegistrationPubKeyCredParamsInner>;
    /**
     * 
     * @type {number}
     * @memberof RequestWebauthnRegistration
     */
    'timeout': number;
    /**
     * 
     * @type {Array<RequestWebauthnRegistrationExcludeCredentialsInner>}
     * @memberof RequestWebauthnRegistration
     */
    'excludeCredentials': Array<RequestWebauthnRegistrationExcludeCredentialsInner>;
    /**
     * 
     * @type {RequestWebauthnRegistrationAuthenticatorSelection}
     * @memberof RequestWebauthnRegistration
     */
    'authenticatorSelection': RequestWebauthnRegistrationAuthenticatorSelection;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistration
     */
    'attestation': string;
    /**
     * 
     * @type {RequestWebauthnRegistrationExtensions}
     * @memberof RequestWebauthnRegistration
     */
    'extensions'?: RequestWebauthnRegistrationExtensions;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationAuthenticatorSelection
 */
export interface RequestWebauthnRegistrationAuthenticatorSelection {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'authenticatorAttachment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'requireResidentKey'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationAuthenticatorSelection
     */
    'userVerification'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationExcludeCredentialsInner
 */
export interface RequestWebauthnRegistrationExcludeCredentialsInner {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExcludeCredentialsInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExcludeCredentialsInner
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationExtensions
 */
export interface RequestWebauthnRegistrationExtensions {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'appid'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'authnSel'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestWebauthnRegistrationExtensions
     */
    'exts'?: boolean;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationPubKeyCredParamsInner
 */
export interface RequestWebauthnRegistrationPubKeyCredParamsInner {
    /**
     * 
     * @type {number}
     * @memberof RequestWebauthnRegistrationPubKeyCredParamsInner
     */
    'alg'?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationPubKeyCredParamsInner
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationRp
 */
export interface RequestWebauthnRegistrationRp {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationRp
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationRp
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface RequestWebauthnRegistrationUser
 */
export interface RequestWebauthnRegistrationUser {
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestWebauthnRegistrationUser
     */
    'displayName'?: string;
}

/**
 * LoginIdApi - axios parameter creator
 * @export
 */
export const LoginIdApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeLoginId} requestChangeLoginId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId: async (requestChangeLoginId: RequestChangeLoginId, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestChangeLoginId' is not null or undefined
            assertParamExists('requestChangeLoginId', 'requestChangeLoginId', requestChangeLoginId)
            const localVarPath = `/api/v1/users/login_id/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestChangeLoginId, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId_1: async (changePassword: ChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'changePassword' is not null or undefined
            assertParamExists('requestChangeLoginId_1', 'changePassword', changePassword)
            const localVarPath = `/api/v1/users/login_id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LoginIdApi - functional programming interface
 * @export
 */
export const LoginIdApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LoginIdApiAxiosParamCreator(configuration)
    return {
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeLoginId} requestChangeLoginId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestChangeLoginId(requestChangeLoginId: RequestChangeLoginId, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestChangeLoginId(requestChangeLoginId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LoginIdApi.requestChangeLoginId']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestChangeLoginId_1(changePassword: ChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestChangeLoginId_1(changePassword, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LoginIdApi.requestChangeLoginId_1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * LoginIdApi - factory interface
 * @export
 */
export const LoginIdApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LoginIdApiFp(configuration)
    return {
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangeLoginId} requestChangeLoginId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId(requestChangeLoginId: RequestChangeLoginId, options?: any): AxiosPromise<void> {
            return localVarFp.requestChangeLoginId(requestChangeLoginId, options).then((request) => request(axios, basePath));
        },
        /**
         * ログインIDの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestChangeLoginId_1(changePassword: ChangePassword, options?: any): AxiosPromise<void> {
            return localVarFp.requestChangeLoginId_1(changePassword, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LoginIdApi - object-oriented interface
 * @export
 * @class LoginIdApi
 * @extends {BaseAPI}
 */
export class LoginIdApi extends BaseAPI {
    /**
     * ログインIDの変更を行うためのリクエストです。送信されたメールアドレス内の認証コードを変更時のリクエストに含めてください。
     * @summary 変更要求
     * @param {RequestChangeLoginId} requestChangeLoginId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoginIdApi
     */
    public requestChangeLoginId(requestChangeLoginId: RequestChangeLoginId, options?: RawAxiosRequestConfig) {
        return LoginIdApiFp(this.configuration).requestChangeLoginId(requestChangeLoginId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ログインIDの変更を行うためのリクエストです。送信されたメールアドレスに変更用のURLが送信されます。
     * @summary 変更
     * @param {ChangePassword} changePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoginIdApi
     */
    public requestChangeLoginId_1(changePassword: ChangePassword, options?: RawAxiosRequestConfig) {
        return LoginIdApiFp(this.configuration).requestChangeLoginId_1(changePassword, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PasswordApi - axios parameter creator
 * @export
 */
export const PasswordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * パスワードの変更リクエストを行います。送信されるメール内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangePassword} requestChangePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (requestChangePassword: RequestChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestChangePassword' is not null or undefined
            assertParamExists('changePassword', 'requestChangePassword', requestChangePassword)
            const localVarPath = `/api/v1/users/password/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestChangePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * パスワードの変更を行います。パスワード変更要求時にメールに添付された認証コードを送信してください。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword_1: async (changePassword: ChangePassword, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'changePassword' is not null or undefined
            assertParamExists('changePassword_1', 'changePassword', changePassword)
            const localVarPath = `/api/v1/users/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePassword, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PasswordApi - functional programming interface
 * @export
 */
export const PasswordApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PasswordApiAxiosParamCreator(configuration)
    return {
        /**
         * パスワードの変更リクエストを行います。送信されるメール内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangePassword} requestChangePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(requestChangePassword: RequestChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(requestChangePassword, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PasswordApi.changePassword']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * パスワードの変更を行います。パスワード変更要求時にメールに添付された認証コードを送信してください。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword_1(changePassword: ChangePassword, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword_1(changePassword, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PasswordApi.changePassword_1']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PasswordApi - factory interface
 * @export
 */
export const PasswordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PasswordApiFp(configuration)
    return {
        /**
         * パスワードの変更リクエストを行います。送信されるメール内の認証コードを変更時のリクエストに含めてください。
         * @summary 変更要求
         * @param {RequestChangePassword} requestChangePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(requestChangePassword: RequestChangePassword, options?: any): AxiosPromise<void> {
            return localVarFp.changePassword(requestChangePassword, options).then((request) => request(axios, basePath));
        },
        /**
         * パスワードの変更を行います。パスワード変更要求時にメールに添付された認証コードを送信してください。
         * @summary 変更
         * @param {ChangePassword} changePassword 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword_1(changePassword: ChangePassword, options?: any): AxiosPromise<void> {
            return localVarFp.changePassword_1(changePassword, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PasswordApi - object-oriented interface
 * @export
 * @class PasswordApi
 * @extends {BaseAPI}
 */
export class PasswordApi extends BaseAPI {
    /**
     * パスワードの変更リクエストを行います。送信されるメール内の認証コードを変更時のリクエストに含めてください。
     * @summary 変更要求
     * @param {RequestChangePassword} requestChangePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PasswordApi
     */
    public changePassword(requestChangePassword: RequestChangePassword, options?: RawAxiosRequestConfig) {
        return PasswordApiFp(this.configuration).changePassword(requestChangePassword, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * パスワードの変更を行います。パスワード変更要求時にメールに添付された認証コードを送信してください。
     * @summary 変更
     * @param {ChangePassword} changePassword 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PasswordApi
     */
    public changePassword_1(changePassword: ChangePassword, options?: RawAxiosRequestConfig) {
        return PasswordApiFp(this.configuration).changePassword_1(changePassword, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WebauthnApi - axios parameter creator
 * @export
 */
export const WebauthnApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebauthn: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/webauthn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerWebauthn: async (registerWebauthnRequest: RegisterWebauthnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerWebauthnRequest' is not null or undefined
            assertParamExists('registerWebauthn', 'registerWebauthnRequest', registerWebauthnRequest)
            const localVarPath = `/api/v1/users/webauthn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerWebauthnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestWebauthnRegistration: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/users/webauthn/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebauthnApi - functional programming interface
 * @export
 */
export const WebauthnApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebauthnApiAxiosParamCreator(configuration)
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWebauthn(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWebauthn(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.deleteWebauthn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerWebauthn(registerWebauthnRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.registerWebauthn']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestWebauthnRegistration(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RequestWebauthnRegistration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestWebauthnRegistration(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['WebauthnApi.requestWebauthnRegistration']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * WebauthnApi - factory interface
 * @export
 */
export const WebauthnApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebauthnApiFp(configuration)
    return {
        /**
         * 登録済みのWebauthnのcredentialを全て削除します。
         * @summary 全件削除
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebauthn(options?: any): AxiosPromise<void> {
            return localVarFp.deleteWebauthn(options).then((request) => request(axios, basePath));
        },
        /**
         * Webauthnの登録を行います。
         * @summary 登録
         * @param {RegisterWebauthnRequest} registerWebauthnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: any): AxiosPromise<void> {
            return localVarFp.registerWebauthn(registerWebauthnRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Webauthn登録のために認証器に送信する情報を取得します。
         * @summary 登録要求
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestWebauthnRegistration(options?: any): AxiosPromise<RequestWebauthnRegistration> {
            return localVarFp.requestWebauthnRegistration(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebauthnApi - object-oriented interface
 * @export
 * @class WebauthnApi
 * @extends {BaseAPI}
 */
export class WebauthnApi extends BaseAPI {
    /**
     * 登録済みのWebauthnのcredentialを全て削除します。
     * @summary 全件削除
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public deleteWebauthn(options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).deleteWebauthn(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Webauthnの登録を行います。
     * @summary 登録
     * @param {RegisterWebauthnRequest} registerWebauthnRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public registerWebauthn(registerWebauthnRequest: RegisterWebauthnRequest, options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).registerWebauthn(registerWebauthnRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Webauthn登録のために認証器に送信する情報を取得します。
     * @summary 登録要求
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebauthnApi
     */
    public requestWebauthnRegistration(options?: RawAxiosRequestConfig) {
        return WebauthnApiFp(this.configuration).requestWebauthnRegistration(options).then((request) => request(this.axios, this.basePath));
    }
}



