/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.api

import org.openapitools.model.ChangeUsername
import org.openapitools.model.Model400Error
import org.openapitools.model.Model401Error
import org.openapitools.model.Model500Error
import org.openapitools.model.RequestChangeUsername
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@Validated
@RequestMapping("\${api.base-path:}")
interface UsernameApi {


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/v1/users/username/requests"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun requestChangeLoginId( @Valid @RequestBody requestChangeUsername: RequestChangeUsername): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            method = [RequestMethod.PATCH],
            value = ["/api/v1/users/username"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun requestChangeLoginId_0( @Valid @RequestBody changeUsername: ChangeUsername): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
