/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.api

import org.openapitools.model.Error
import org.openapitools.model.RegisterWebauthnRequest
import org.openapitools.model.RequestWebauthnRegistration
import org.openapitools.model.WebauthnRegistration
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@Validated
@RequestMapping("\${api.base-path:}")
interface WebauthnApi {


    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/api/v1/users/webauthn"],
            produces = ["application/json"]
    )
    fun deleteAllWebauthn(): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/api/v1/users/webauthn/{credentialId}"],
            produces = ["application/json"]
    )
    fun deleteWebauthn( @PathVariable("credentialId") credentialId: kotlin.String): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/v1/users/webauthn"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun registerWebauthn( @Valid @RequestBody registerWebauthnRequest: RegisterWebauthnRequest): ResponseEntity<WebauthnRegistration> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/v1/users/webauthn/requests"],
            produces = ["application/json"]
    )
    fun requestWebauthnRegistration(): ResponseEntity<RequestWebauthnRegistration> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
