openapi: 3.0.0

info:
  version: 1.0.0
  title: SecureStream API
  description: SecureStream APIの仕様書です

servers:
  - url: http://localhost:8081
    description: ローカル環境

paths:
  /api/v1/users/login_id/requests:
    $ref: './paths/api/v1/users/login_id/requests.yml'
  /api/v1/users/login_id:
    $ref: './paths/api/v1/users/login_id.yml'
  /api/v1/users/password/requests:
    $ref: './paths/api/v1/users/password/requests.yml'
  /api/v1/users/password:
    $ref: './paths/api/v1/users/password.yml'
  /api/v1/webauthn/request:
    $ref: './paths/api/v1/webauthn/request.yml'
  /api/v1/webauthn:
    $ref: './paths/api/v1/webauthn.yml'

components:  
  securitySchemes:
    Bearer:
      $ref: './components/securitySchemas/bearerAuth.yml'
