openapi: 3.0.0

info:
  version: 1.0.0
  title: SecureStream API
  description: SecureStream APIの仕様書です

servers:
  - url: http://localhost:8081
    description: ローカル環境

paths:
  /api/v1/users/login_id/requests:
    $ref: './paths/api/v1/users/login_id/requests.yml'
  /api/v1/users/login_id:
    $ref: './paths/api/v1/users/login_id.yml'
  /api/v1/users/password/requests:
    $ref: './paths/api/v1/users/password/requests.yml'
  /api/v1/users/password:
    $ref: './paths/api/v1/users/password.yml'
  /api/v1/users/webauthn/requests:
    $ref: './paths/api/v1/users/webauthn/requests.yml'
  /api/v1/users/webauthn:
    $ref: './paths/api/v1/users/webauthn.yml'
  /api/v1/users/social_login/urls:
    $ref: './paths/api/v1/users/social_login/urls.yml'
  /api/v1/users/social_login/code/{provider}:
    $ref: './paths/api/v1/users/social_login/code/provider.yml'
  /api/v1/users/social_login/{provider}:
    $ref: './paths/api/v1/users/social_login.yml'

components:  
  securitySchemes:
    Bearer:
      $ref: './components/securitySchemas/bearerAuth.yml'
